### ISSUE TITLE
Automatically upgrade to higher mem GPU nodes after pods fail due to memory issues

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/kiosk#103]
Currently, pods that exceed their memory allocation appear to crash without leaving behind logs or records of termination. Restarting the cluster with GPU nodes that have more memory typically resolves the problem. Building this into an automated feature would improve the robustness of the system.

**Comment by willgraf** [comment]
It looks like this might be possible [with GKE API](https://cloud.google.com/kubernetes-engine/docs/how-to/node-pools).

**Comment by willgraf** [comment]
I'm going to close this issue, as it pertains to training, which has been removed from the current scope of work.
