### ISSUE TITLE
kiosk container OS varies based on environment that launches it

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk#114]
On gcloud bastion running the kiosk container, I find that the `/proc/version` file contains the following:

```
Linux version 4.15.0-1028-gcp (buildd@lgw01-amd64-045) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #29-Ubuntu SMP Thu Feb 7 18:20:08 UTC 2019
```

Gcloud OS:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

These results differ from running the `kiosk` on my local machine with OS:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

and we see a `/proc/version` of:

```
Linux version 4.4.0-83-generic (buildd@lgw01-29) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017
```

---

Additionally, on the local machine, we succeed and do not see a prompt asking to confirm `(Y/n)` while we do ask for confirmation on the gcloud instance.  I believe this confirmation page is the problem.

<img width="1154" alt="Screen Shot 2019-04-02 at 4 36 57 PM" src="https://user-images.githubusercontent.com/7930703/55442952-9f0d0800-5565-11e9-8b58-71cd2cabac0c.png">
<img width="1154" alt="Screen Shot 2019-04-02 at 4 37 09 PM" src="https://user-images.githubusercontent.com/7930703/55442953-9f0d0800-5565-11e9-8423-9b43a5a0b346.png">

---

Docker versions:
local - `Docker version 18.03.1-ce, build 9ee9f40`
dind/dind -  `Docker version 18.06.1-ce, build e68fc7a`
gcloud - `Docker version 18.09.4, build d14af54266`

**Comment by osterman** [comment]
@willgraf what you are inspecting is the version of the Linux kernel. Containers are not virtual machines, so we have no control over the kernel. On a mac, it will be the version of the VM used "under the hood", while on Linux it will be the container. 

Also, what version of `geodesic` are you running? Have you tried upgrading `geodesic` and thereby also upgrading `gcloud`? Where are you using `dind`?

-Erik

**Comment by willgraf** [comment]
OK. Interesting, so it's not a different OS (good, my mind was getting blown).

`dind/dind` is being run from our own Linux box (described as local machine in the issue).

It looks like our geodesic version is:

```
FROM cloudposse/build-harness:0.9.0 as build-harness

FROM cloudposse/geodesic:0.32.5
```

I am not sure how stale these are.

**Comment by osterman** [comment]
We've had [quite a few releases](https://github.com/cloudposse/geodesic/releases) since then. You can try to upgrade, but not sure what the upgrade path would be without trying it.

**Comment by willgraf** [comment]
Closing this as the behavior is normal (kernel vs OS)
