### ISSUE TITLE
Helmfile deployment during cluster startup fails

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#15]
During cluster startup, the helmfile deployment always makes it to file `0220.tf-serving-redis-interface.yaml` and then fails on that file with `Error: unable to move current charts to tmp dir: rename /conf/charts/tf-serving-redis-interface/charts /conf/charts/tf-serving-redis-interface/tmpcharts: invalid cross-device link`.

**Comment by dylanbannon** [comment]
This bizarre issue hasn't shown up for a while. If it doesn't reappear within the next week or so, I'll just chalk it up to a transient error during development and close this issue.

**Comment by osterman** [comment]
So this is happening with an old release of helmfile.

See: https://github.com/helm/helm/issues/2998

**Comment by dylanbannon** [comment]
Well, helm/helm#2998 hasn't been fixed, although a commenter in that thread mentions the following as a workaround:
```
Ah, found one: manually call helm package on dependencies, specifying the destination chart/ directory of the parent chart.
```

@osterman, what's your recommendation: do we leave this issue open until someone fixes this in helm/helm, do we try implementing the workaround, or do we just not worry about this issue as long as it agrees not to show up again?

**Comment by willgraf** [comment]
This issue is resolved.  Our helmfile deployments are wrapped in a retry loop, and we have updated our base kiosk image to the latest from cloudposse
