### ISSUE TITLE
GKE cluster upgrading?

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#160]
Looking the GKE's web interface, it looks like (some?) clusters are experiencing downtime immediately after creation, due to cluster upgrading. I think this might be leading to the `Lost connection to pod` error @enricozb mentioned in #156 . the whole reason we switched to regional clusters a while back was to avoid this mandatory upgrade, since it blocks helmfile deployment and, in this case, might be leading to a confusing new error.

If someone can confirm that they are seeing cluster downtime due to GKE upgrading the cluster, I'll find a fix for this.

**Comment by willgraf** [comment]
I can confirm that one of my new clusters immediately went into "upgrading cluster master" status.

HOWEVER, once it was updated, the ingress continued to fail.  I then "Exited" the installation, dropped to shell, and tried to run the `make helmfile/create/all` command.  This also continued to fail despite the master being upgraded.

**Comment by dylanbannon** [comment]
You know, I have a theory. I'm going to hypothesize that the only reason we have a problem with the ELK stack sometimes not deploying (#156) is because those are the helm files that are in the middle of deploying whenever GKE takes the master down for upgrading. Then, when the master comes back, somebody has lost track of some piece of cluster state and the ELK deployments can't recover, getting stuck in that weird loop.

**Comment by willgraf** [comment]
Do we still see this issue now that the ELK stack is optional?

**Comment by dylanbannon** [comment]
This issue was definitely independent of ELK, but I haven't seen this in a while. GKE's internal workings are mysterious and too profound for our understanding sometimes.

If this comes up again later, we should revive this issue.
