### ISSUE TITLE
Rewrite kiosk menu in Python

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#161]
The current kiosk menu is a monument to the power of bash scripting but, because of that, it's nearly impossible to teach undergrads how to tweak it. A Python script would not only be easier to maintain, it would actually allow us to get help from undergrads a lot more easily.

The first step in this process would be finding an appropriate graphics module for Python. I know that Python has a built-in `tk` module, but there are probably better options out there. When selecting a graphics module, I think we should prioritize 1) ease of coding and 2) quality of resulting graphics.

**Comment by willgraf** [comment]
I want to close this as our `alpine` base image prevents us from using a Python-based GUI.  I believe that with our base image, we are restricted to using `dialog`.

**Comment by willgraf** [comment]
I'm closing this issue, as `alpine` will not support a Python GUI.
