### ISSUE TITLE
LoadBalancers and Target Pools are not being deleted properly

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk#162]
An accumulation of un-deleted load balancers caused further `ingress` and `openvpn` deployments to fail (#156).  Load balancers and their target pools should be deleted during cluster destruction.

**Comment by dylanbannon** [comment]
My theory with these is the same as for #154. Namely, that they are created via `helm` (I'm guessing from the `nginx-ingress` chart) and then, if the cluster destruction fails and we have to delete the cluster manually, are not deleted along with the cluster.

A possible solution to this problem (some resources created from within the kiosk not being recognized by Google Cloud as being intrinsically tied to a given Kubernetes cluster) might be to change the service account that helm uses to request resources. One, I'm not sure that changing out the Google Cloud service account on the fly is feasible for us. Two, I'm not sure how google Cloud determines what resources are intrinsically part of a Kubernetes cluster, so I'm not actually certain that requisitioning resources with the right account would even fix this issue.

So really, this is more for documentation than anything else.
