### ISSUE TITLE
Request: Use prometheus to scrape logs and deprecate ELK stack

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk#164]
We are really just using the entire ELK stack to grep log files for some key numbers.  Can we replace the entire ELK stack with prometheus+grafana? This would improve cluster creation (ELK is the #1 offender during creation) and allow for future scaling based on metrics in the logs.  I am not sure how feasible this is, but since logstash is just using `grok` to scrape the logs, maybe there is another prometheus chart that can do it as well.

---

Maybe the [grok_exporter](https://github.com/fstab/grok_exporter) can help with this.

**Comment by osterman** [comment]
prometheus will just give you metrics. those are valuable, but when you are trying to triage things having the centralized logging can be nice.

Btw, we ship a tool in Geodesic called `stern` that can also be useful for grepping logs across all pods. 

https://github.com/wercker/stern

**Comment by willgraf** [comment]
Wow `stern` looks pretty useful!  Thanks for pointing to that.

**Comment by willgraf** [comment]
I am closing this as ELK was deprecated/made optional in #171 and `stern` resolves most of our needs.

I still think that using prometheus with `grok` could be interesting but for now there is no need.
