### ISSUE TITLE
Un-deleted cluster resources may prevent future deployments.

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk#169]
As noted in several other issues, some cloud resources may not be properly deleted, or if cluster deletion fails for some reason, they may be stranded. 

The following resource types have prevented clusters from being created, and the resources had to be manually deleted from the Cloud console.

See [here](https://github.com/vanvalenlab/kiosk/issues/69#issuecomment-439495272) for a suggestion as to how this could be prevented or maintained, though it is an open problem.

* GKE LoadBalancers and Target Pools (#162)

* GKE Service Accounts (#113)

* GKE Persistent Disks (#140)

* AWS VPCs (#67)

* AWS Launch configurations, Network Interfaces (#69)

**Comment by willgraf** [comment]
I want to relate this to #174 as the some of the resources (Persistent Disks especially) can cost money long after the cluster is deleted.

**Comment by willgraf** [comment]
I believe this has been largely resolved with more robust cluster destruction, specifically #199.

However, I may want to leave this issue up as a warning for future users.

**Comment by dylanbannon** [comment]
I think we're actually in a position to deal with the case where cluster creation or destruction fails and leaves resources stranded, so let's move this discussion to #274.
