### ISSUE TITLE
Implement CI/CD

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#176]
We need some sort of automated testing for this project.

**Comment by osterman** [comment]
Signup for GitHub actions for your org. This will be perfect for you guys.

**Comment by osterman** [comment]
https://github.com/features/actions/signup/?account=osterman

When you signup, make sure you select the “vanvalenlab” in the drop down.

**Comment by willgraf** [comment]
Duplicate issue to  #176

**Comment by MekWarrior** [comment]
#198 uses automated builds but does not include tests. If required we can migrate off travis.

**Comment by willgraf** [comment]
This looks to be a duplicate of #60.  I will close the older issue as the discussion here is a bit more helpful.

**Comment by dylanbannon** [comment]
We have a bare bones integration testing framework in #268. Further work on this issue is occurring in #281.

**Comment by dylanbannon** [comment]
Closed by #268!
