### ISSUE TITLE
"Error" displays in corner during kiosk configuration

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/kiosk#183]
![image](https://user-images.githubusercontent.com/45578681/70569019-f9775300-1b4d-11ea-9377-a0a6a5dec64f.png)

This is displayed in the corner for various lengths of time (sometimes just flashes briefly, sometimes visible for a few seconds) after most configuration steps (configuring for google).

**Comment by willgraf** [comment]
This is due to improperly ordered options using `dialog`. All "common options" should be first, followed by "box options". We had a box option intermingled with common options.
