### ISSUE TITLE
Errors during GKE cluster creation are ignored

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/kiosk#184]
![kiosk troubleshoot](https://user-images.githubusercontent.com/45578681/70569521-edd85c00-1b4e-11ea-8607-aac24e52af57.png)

Trying to create a cluster on my personal gcloud project fails because of an insufficient project quota. Since the cluster creation fails, kiosk assumes that it is because a cluster already exists (it doesn't). We then move on to the next step, but nothing works because no cluster actually exists.

**Comment by MekWarrior** [comment]
The resolution of this issue should also address a problem uncovered by #236 

Our current use of the variable CLOUD_PROVIDER as a flag to determine whether a cluster is ready to be created (configured correctly) is faulty. 

We should be aware that stale credentials on startup (cached in preferences) could be problematic going forward.

**Comment by willgraf** [comment]
It looks like our helmfile script `gke-helmfile-deployment.sh` also will retry each helmfile 3 times, then move on to the next helmfile.  This should also probably not be ignored.

**Comment by MekWarrior** [comment]
We have addressed my previous comment re: stale cached credentials by the patch suggested in #236 as well as the echo of cluster creation configuration settings in: #242
