### ISSUE TITLE
Spot detection fails with skimage error

### ISSUE THREAD

**Issue by elaubsch** [vanvalenlab/kiosk#204]
Job Failed: Traceback (most recent call last): File "/usr/src/app/redis_consumer/consumers.py", line 192, in consume status = self._consume(redis_hash) File "/usr/src/app/redis_consumer/consumers.py", line 1444, in _consume image = skimage.transform.rescale(image, 2, anti_aliasing=False) NameError: name 'skimage' is not defined

Used sample SeqFISH data from deepcell.org

**Comment by willgraf** [comment]
I think this has now been resolved. Issue was fixed in master branch for the consumers, but had not been updated in prod.

Could you please re-test and if it works this issue can be closed.

**Comment by willgraf** [comment]
I've tested this myself, and can confirm it works. Closing this issue.
