### ISSUE TITLE
jupyter nav bar link should go to an actual notebook

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#21]

**Comment by dylanbannon** [comment]
@willgraf do you think we should just spawn an empty jupyter notebook is the user clicks the Jupyter button on the homepage?

**Comment by willgraf** [comment]
That is not a bad idea, though wouldn't it take a long time to load the
jupyter notebook due to GPU scaling?

What do we want the jupyter button to do?  Maybe we should just remove it.

**Comment by willgraf** [comment]
I think we can also close this issue, as the jupyter notebook requirement has been removed.

**Comment by dylanbannon** [comment]
@willgraf Agreed. We don't support this anymore, so it's time to close this issue down.
