### ISSUE TITLE
Add info to docs about requirements for bucket organization and models

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/kiosk#219]
- Describe expected bucket organization for tf-serving
- How to export models (maybe redirect to deepcell docs, but content will need to be written either way)
- Are there any additional bucket folder requirements?

**Comment by willgraf** [comment]
The bucket will need a folder called `models` with each exported model file inside it.

`/models` can actually be configured to be different, it is the value of `MODEL_PREFIX` environment variable in the `tf-serving` helmfile.

Additionally, files will be uploaded to `/uploads`, (though no input from users is required for this.).  This value is also configurable with the `UPLOAD_PREFIX` environment variable in the `frontend` helmfile.

Finally, output data is saved in `/output` inside the bucket.  I think this is also configurable but I cannot find it at the moment.

**Comment by msschwartz21** [comment]
Docs updated accordingly.
