### ISSUE TITLE
killed kiosk process. run new kiosk but helm errors out.

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk#23]
The kiosk process was killed but the cluster is still up.  I ran `make run` again to start a new kiosk process, and dropped to the shell.  `helm list` and `helmfile` cause the following error:

```
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused
```

`kubectl` causes:
```
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by dylanbannon** [comment]
I think this is probably expected behavior, since the new kiosk does not have access to the keypair that was used for communication with the old cluster. @osterman can you comment on this?

**Comment by osterman** [comment]
> The connection to the server localhost:8080 was refused

See: https://docs.cloudposse.com/faq/running-kubectl-fails-connection-refused/

**Comment by dylanbannon** [comment]
@willgraf, can you recreate this error and see if the fix linked to by @osterman takes care of it? If so, I can make a branch where dropping to the shell before creating a cluster within a kiosk (implying that you want to interface with a pre-existing cluster) leads to the user being prompted to enter the name of the cluster they want to interact with.

**Comment by dylanbannon** [comment]
Also, @willgraf, did you go through the configuration process for whichever cloud you were using before dropping to the shell in your second kiosk? If not, is that sufficient to fix this? If so, then maybe it makes sense to just document this in the troubleshooting doc?

**Comment by willgraf** [comment]
I'm going to close this as stale, since it has not been encountered in over a year.
