### ISSUE TITLE
Improve menu aesthetics

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk#234]
**Is your feature request related to a problem? Please describe.**
The menu windows are of variable width and height and do not have consistent back-title and titles. Additionally, the GPU box message is too long, causing the GPU selection box to not fit all the values.  `radiobox_from_array` should likely have a max height value as well.

**Describe the solution you'd like**
Menus should be updated for a consistent appearance with reasonable sizes.

- [x] Max size for `radiobox_from_array`
- [x] Shorter GPU warning message (1 line max).
- [ ] Minimum/Maximum height/width for all boxes (specifically Loading boxes).
- [x] Consistent back-title and title in all boxes.

**Comment by MekWarrior** [comment]
It would be nice to include a "Confirm" box for cluster creation. This should include a warning that if the operation is aborted midway (or that cluster creation doesn't finish successfully) it will be necessary to delete resources from the cloud console.

**Comment by willgraf** [comment]
Minor issue, but the `tailcmd` portion has a shadow that hits the edge of the window.  I think I would prefer this window to be slightly smaller:

<img width="976" alt="Screen Shot 2020-01-30 at 2 03 52 PM" src="https://user-images.githubusercontent.com/7930703/73494477-72827200-4369-11ea-870c-e93a543385bc.png">

**Comment by willgraf** [comment]
#270 sets a maximum height of the `radiobox_from_array` function.

**Comment by willgraf** [comment]
The remaining TODO in the checklist above is for standardizing the widths/heights of the message boxes.  This may be difficult to do well, as each box's width is related to the text inside.

While some boxes may be a bit wider, it is for better display of the text inside.  This is desired, IMO, as the message text looking off is much more distracting than the box being slightly wider or skinnier.
