### ISSUE TITLE
Kiosk doesn't recongize my google credentials on first try

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#249]
**Describe the bug**
When I try to configure a cluster, I'm prompted to go to the long google link and paste the confirmation code. When I paste the code, I get an error message from the Kiosk saying that authentication failed. After that, if I select "Configure GKE" again, all of my google information has been recognized and configuration proceeds smoothly.
I have only observed this behavior within the docker-in-docker VM, so I'm not sure if it happens elsewhere.

**To Reproduce**
1. Spin up dind Docker container.
2. Run kiosk and choose configure GKE.
3. See error

**Expected behavior**
There shouldn't be a failure of authentication.

**Desktop (please complete the following information):**
 - OS: dind

**Additional context**
Only observed inside dind. I will try to test outside dind.

**Comment by willgraf** [comment]
This indeed does seem to happen on `dind`:

```bash
ERROR: (gcloud.auth.login) The project property is set to the empty string, which is invalid.
To set your project, run:

  $ gcloud config set project PROJECT_ID

or to unset it, run:

  $ gcloud config unset project
```

It looks like this is related to the upgrade of `gcloud` from #246. Since then we are supposed to include the `--project` flag.

Maybe we can catch this error directly and ignore it?

**Comment by dylanbannon** [comment]
After selecting `Configure GKE` the second time, I'm not prompted to copy-paste the confirmation code. Instead is asks me to choose a Google account from a list (where mine is the only entry) and then I'm asked to choose a Google Cloud project from a similar list.

If this doesn't normally fail for anyone else, then it's because there's already a default project configured for `gcloud` in the environment you're using. If that's the case, then it's possible that a user will have `gcloud` configured but with a different project selected as the default, right? If so, that could lead to bad things, so I'm thinking we should take people to the "choose a project" dialog by default after they paste the confirmation code. That would close this issue and avoid a potentially embarrassing situation with a self-righteous PI down the road.

I'll assign this to myself, if you're in agreement on a course of action, @willgraf.

**Comment by willgraf** [comment]
I think the root cause is an update to `gcloud` where it changed the behavior of `gcloud auth login`.  Now it wants us to include a project ID in the command, which it is telling us in the error.

However, it looks like even though we get the project error, the authentication works and users can "continue as ..." and deploy a cluster.  The account seems to be cached in their `CLOUDSDK_CONFIG` directory, and so we avoid calling another `auth login` on the second try.

Maybe we can capture ONLY the error output in a variable, and check if the known error is a substring?

**Comment by dylanbannon** [comment]
It looks like there are two ways to do this:
1) capture the error in a file, open the file, run a regex on the file to see if it contains the error text
or
2) capture the error in a variable and run a regex on that to see if it contains the error text.

2 is simpler logically, but 1 has simpler syntax.

Solution 1:
https://stackoverflow.com/a/637834

Solution 2:
https://stackoverflow.com/a/6317938
