### ISSUE TITLE
Kiosk Shell freezes with large outputs

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#252]
**Describe the bug**
When you choose the `Shell` menu option after creating a cluster, the shell can freeze and become non-responsive if you ask it to print too much information to the terminal. If you're running the terminal inside a Docker container, after this, the kiosk (and, by extension, the cluster itself) becomes inaccessible via the container. As far as I know, at this point, you can only assess the cluster via Google's browser-based terminal.

(It's possible, I guess, that the shell might recover functionality if you wait long enough for it to churn through the output but, in practice, this is often longer than I'm willing to wait. I.e., >10 minutes.)

**To Reproduce**
An example of a command that could produce this behavior might be executing `kubectl logs [pod_name]` on a pod that produces a large log volume (`prometheus-adapter`, for example) inside a cluster that's been running overnight.

**Expected behavior**
Ideally, the terminal wouldn't sieze up.

**Desktop (please complete the following information):**
 - OS: dind

**Additional context**
May only be a problem in dind?

**Comment by willgraf** [comment]
I think it may just be a `kubectl` problem when getting very large output. To prevent this issue, you can use `--tail N` to only get the last N lines.

There is also `stern`, which can tail all logs based on a deployment name.

**Comment by willgraf** [comment]
Let's add a warning about this to the advanced docs.

**Comment by dylanbannon** [comment]
@willgraf 
Agreed.

This bug really only affects developers, so I don't think fixing it should be a priority right now (even assuming it's possible).

Like you suggested, documenting and providing preemptive guidance (suggesting that people use `tail`, etc.) is probably the most efficient solution.
