### ISSUE TITLE
cluster startup commands should fail gracefully

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#26]
You know that feeling when you try to startup a cluster, but then it fails for whatever reason, and then you fix that problem and try to start it again, and this time it just fails because it had already executed some of the startup commands on the first try, before failing, and doesn't want to remake a bucket or whatever? We should have all of the resource acquisition portions fail silently if the resource already exists. Or maybe just print a warning?

**Comment by willgraf** [comment]
Fixed by #52
