### ISSUE TITLE
Consolidate GitHub Actions and Travis builds

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk#269]
With PR #268 we are using GitHub Actions to do automated testing.  Meanwhile, we are using Travis CI to create releases.  These services should likely be consolidated.

In regards to Travis CI vs GitHub Actions, I would personally rather use Travis CI merely because I have never used GitHub Actions.

Since our test/build services do not need to be served on the same system, let's make an issue to do some due diligence on which platform we should use and not have this block the current PR.

_Originally posted by @willgraf in https://github.com/vanvalenlab/kiosk/pull/268#issuecomment-589407785_

**Comment by dylanbannon** [comment]
I'm going to vote for TravisCI, only because using GitHub Actions definitively locks development of the Kiosk (or future derivatives of it) to GitHub. I think using a git platform-agnostic CI service makes us a little more attractive, on balance, to potential contributors.

**Comment by dylanbannon** [comment]
We went with TravisCI. Will be fixed when #268 merges.

**Comment by dylanbannon** [comment]
Closed by #268.
