### ISSUE TITLE
some users are using `sudo` to run the `kiosk`

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#31]
Some users have docker installed in such a way that they don't have unprivileged access to it, leading to a whole bunch of kiosk startup commands requiring `sudo` and prehaps(?) leading to issues with AWS deployment.

My thought is that, ideally, we would provide a brief description in the README about how users can modify their Docker installation to no longer need to use `sudo` and state that, should they prefer to keep using sudo, some services may not work.

**Comment by dylanbannon** [comment]
Can I get your input on this, @willgraf?

**Comment by willgraf** [comment]
I think I resolved this on the EC2 bastion machine by adding the current user to the `docker` user group.

**Comment by willgraf** [comment]
Using a gcloud instance to run the kiosk, I found that my user was in the docker group (`docker -v` works) but had to use `sudo` to run `make docker/build`.

**Comment by dylanbannon** [comment]
Regarding @willgraf's issue, I had to learn this first-hand just now, but it turns out that `docker -v` will print out version info without the current user being a member of the `docker` user group, so the rest of what you observed makes sense.
