### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#40]
Let's assume that our audience is wet lab biologists, who might have very little knowledge regarding programming or cloud computing. We then need:

- Detailed documentation, beyond what's in the README
- Detailed videos of different portions of the setup process (e.g., a video of setting up Google Cloud)
- Perhaps a Readthedocs

**Comment by willgraf** [comment]
Duplicate issue to #176.

BATS is hard so I'm closing this one instead.
