### ISSUE TITLE
GKE only allows alphanumeric characters and hyphens in service names

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk#43]
`kiosk` should not allow users to enter bad service names without at least warning the user of accepted character sets.

**Comment by dylanbannon** [comment]
@willgraf Would it be sufficient to silently reformat names? That's the current state of #78.

**Comment by willgraf** [comment]
> Thanks, @osterman. That's nifty!
> 
> @willgraf Would it be sufficient to silently reformat names? That's the current state of #78.

Yes, I think that should be fine.  My two concerns:

1. Will we silently reformat the bucket name they pick? That worries me a bit as all their data is there and they may not understand which bucket is which.

2. Do AWS and GKE have the same formatting restrictions?  If one is more strict, we can reformat to that, but if they have conflicts in their formatting that may get tricky.

**Comment by osterman** [comment]
Yea, good points. Probably best to validate & error, just I'm not sure how to best surface that in the relatively primitive UI.
