### ISSUE TITLE
Console got stuck at Create GKE Cluster step

### ISSUE THREAD

**Issue by wonjho** [vanvalenlab/kiosk#474]
The creating GKE cluster step takes forever to finish.

<img width="668" alt="微信图片_20240722103355" src="https://github.com/user-attachments/assets/3007ba97-0211-454a-b168-81879cb756ee">

gcloud version
Google Cloud SDK 471.0.0
alpha 2024.03.29
beta 2024.03.29
bq 2.1.3
bundled-python3-unix 3.11.8
core 2024.03.29
gcloud-crc32c 1.0.0
gke-gcloud-auth-plugin 0.5.8
gsutil 5.27

Thank you very much for any help and thoughts!!

**Comment by rossbar** [comment]
I don't think there's much we can do to help chase this down. This infrastructure-as-code pattern conflates cloud config/account setup info with the "code", so it's very difficult to find where problems lie. All I can say is the deployment pattern is working for the primary [deepcell.org](https://deepcell.org/) deployment.
