### ISSUE TITLE
learn how to use REDIS

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#49]
What is REDIS and how does it work?

(Or, how can we best leverage a combination of queues and hashmaps in order to 1) ensure that no job gets accidentally processed twice, and 2) the frontend is able to monitor the status of jobs?)

**Comment by willgraf** [comment]
Fixed by various PRs in the base helm images.

Now the redis-consumer is using a queue as well as the rest of the data hashes.
