### ISSUE TITLE
Adjust cluster limits for GKE (and AWS?)

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#55]
On GKE, now that we've implemented training, we're often running out of resources in our node pools. The sizes of these node pools should be adjusted so that this isn't an issue. It would be best if we could warn users about approaching node pool limits or handle an exhaustion of a node pool gracefully.

There's probably a similar situation on AWS.

**Comment by dylanbannon** [comment]
@vanvalen can you comment on what an appropriate upper limit would be for the GPU node pool?

**Comment by dylanbannon** [comment]
@vanvalen suggests using P100 GPUs with a min of 0 and a max of 4 for defaults. He also suggests giving users the option to specify mins, maxes and (I believe) GPU types. I'll open yet another issue for that.

**Comment by dylanbannon** [comment]
We're not doing anything to warn users about impending node pool limits, but we do allow users to set node pool sizes with #58.

Perhaps this issue can be closed with a little documentation about GPU requirements of different processes.

**Comment by willgraf** [comment]
@dylanbannon I agree (over a year later). This issue can be closed, as we have removed training from the functionality and do not have this issue with the prediction workflow.

**Comment by dylanbannon** [comment]
@willgraf Yep, agreed. Closing, until such a time as we re-implement training.
