### ISSUE TITLE
Scaledown for training-job

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#56]
The training-job may not be able to scale back up after scaling down. If someone has free time, they should investigate whether there's any issue with this.

**Comment by willgraf** [comment]
I think this is now a non-issue.  We monitor job `parallelism` and if there is pending work we increase the parallelism up to GPU-NODE-MAX.

Scaling down is handled by the `kiosk-autoscaler` and if there are no more jobs to work on, the parallelism is set to 0, and no training jobs will run.
