### ISSUE TITLE
Implement automated testing

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#60]
As issue #59 underscores, we need some way to definitively saying that a branch is ready to merge into `master`. Since this project looks like it'll be with us for a while to come, this is probably a sound time investment.

@willgraf what are your thoughts on how was should go about implementing automated testing?

**Comment by dylanbannon** [comment]
Upon @osterman's suggestion, we'll be implementing tests using https://github.com/bats-core/bats-core

Specific things to test (feel free to expand):
- [ ] cluster creation on both AWS and GKE
- [ ] GPU scale-up for both predict and training jobs on both AWS and GKE

**Comment by willgraf** [comment]
Closing this issue as it is duplicated (as mentioned above).
