### ISSUE TITLE
Kiosk deployment fails when Bucket name is already in use.

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk#64]
Bucket names are global, and if other users not in the organization have taken the bucket name, the deployment will fail.  This should be better brought to the user's attention to have them re-configure with another bucket name.
<img width="1413" alt="screen shot 2018-11-12 at 12 31 49 pm" src="https://user-images.githubusercontent.com/7930703/48373631-3cc76f80-e677-11e8-97eb-214ef363ca68.png">

**Comment by osterman** [comment]
(or remove this daunting task an generate unique bucket names; users are bad at naming things)
