### ISSUE TITLE
kiosk shell should use "deepcell" namespace by default

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk#65]
It's annoying to do `kubens deepcell` every time I drop to the shell.

**Comment by osterman** [comment]
This is only possible after running `kubectl export kubecfg`. We can discuss some options for doing this by hooking into the `prompt_command` hooks interface in `/etc/profile.d/prompt.sh`

**Comment by willgraf** [comment]
Resolved in #111
