### ISSUE TITLE
AWS too many VPCs error

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#67]
This is what you see when you have too many VPCs on your AWS account:
![aws_vps_limit_error](https://user-images.githubusercontent.com/21188071/48639441-786c7d00-e988-11e8-9c3a-367414888131.png)

We need to
1) document this in the troubleshooting document
and, potentially,
2) start deleting VPCs upon AWS cluster shutdown, since each AWS cluster gets its own VPC.

This is the second time I've seen this error come up.

**Comment by willgraf** [comment]
Closing this as the issue is now being tracked by #169.
