### ISSUE TITLE
GPU scaling fails under certain circumstances

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#71]
Adapted from a comment in #58.

I tested GPU scaling a lot and here's what I found:
On `master` right now (as of the merging of `appropriate-cluster-sizing`):
GKE-K80-predict -> works
AWS-K80-predict -> works
GKE-K80-train -> works
AWS-K80-train -> doesn't work
GKE-P100-predict -> doesn't work
GKE-P100-train -> works

This shows that everything that works in master works in this branch, and that there are two different cases (of those tested here) that fail. I'm going to open one issue about those cases, but I suspect they have different causes, since they involve different clouds, different GPUs, and different cluster functionality.

**Comment by dylanbannon** [comment]
@osterman can we get your thoughts on this?

**Comment by dylanbannon** [comment]
For the record, when I say GPU scaling "doesn't work" in a certain circumstance, what I mean is that the `cluster-autoscaler` doesn't scale up the GPU node pool in response to the creation of a pod which requires `nvidia.com/gpu`. This is indicated in the recent events section of the `kubectl describe pod [pod_that_requires_nvidia.com/gpu]` output.

**Comment by willgraf** [comment]
UPDATE:

#73 Configured tf-serving GPU nodeSelector to be whichever GPU type is chosen by the user.  After implementing this fix, a "Trigger" event was called by both the training pod and the tf-serving pod for all 3 GKE GPU types (`K80`, `P100`, and `V100`).  GKE GPU scaling seems to work well.

HOWEVER:
**AWS Scaling consistently gets a `NotTriggered` event for all training pods.**
AWS prediction GPU scaling works as expected.

**Comment by dylanbannon** [comment]
Fixed by #81, but now I'm kind of amazed that the training jobs were being scheduled properly in GKE. It seems like they shouldn't have been able to be scheduled onto any GPU node without the necessary toleration.
