### ISSUE TITLE
redis-master, our cluster database, is not under the control of a replicaset and will not respawn if the node it's hosted on fails

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#79]
Is this desirable behavior, @osterman?

**Comment by osterman** [comment]
Consider upgrading to the latest chart. It uses a stateful set
https://github.com/helm/charts/blob/master/stable/redis/

**Comment by osterman** [comment]
Oh, I think the misunderstanding is that it uses a statefulset instead of a replica set to manage pods. This is because of the durable storage. There is another redis chart called “redis-ha” that might work better, but haven’t tried it.

**Comment by osterman** [comment]
ReplicaSets are not suitable for applications with persistent storage because a volume can only be attached to one instance at a time.

**Comment by willgraf** [comment]
The latest chart is indeed using a StatefulSet, and I believe this issue is resolved.
