### ISSUE TITLE
Cluster destruction partially fails

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#8]
When I use the Destroy command from the main menu to destroy the cluster, it never finishes execution. It never succeeds in deleting the VPC and its associated DHCP resource.

When I look around afterwards, I see that 1) the keypair located in `/localhost/.geodesic` is still present, and 2) the S3 bucket that stored the cluster configuration wasn't deleted.

Perhaps this is an issue with the newer version of Geodesic?

**Comment by osterman** [comment]
Can you paste a screenshot something that conveys what's happening?

**Comment by dylanbannon** [comment]
The output is kind of cramped, but I think you get the idea. It just stays like that forever.

![kubernetes_destroy_fail](https://user-images.githubusercontent.com/21188071/45393258-9956d180-b5d7-11e8-84ec-c38c6468db94.png)

**Comment by dylanbannon** [comment]
Resolved.
