### ISSUE TITLE
start tf-serving on cpu, and switch to gpu when necessary

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#83]
In discussion with @MekWarrior and @willgraf, it's become apparent that we could probably run tf-serving on a CPU in a lot of use cases (i.e., low image volume) and still see reasonable processing times. A potential cost- and time-saving architecture upgrade, then, would be to startup tf-serving on cluster startup, running on a CPU. Then, if image prediction volume exceeds some threshold (either image backlog or images/time over a given period recently; threshold will need to be determined via benchmarking), then we deploy another tf-serving on GPU and move prediction over to that once the GPU instance and pod are ready. Once the backlog has been resolved, we can move back down to CPU.

An analogy might be made to scaling up computational resources by scaling up pod number but, in this case, we're scaling up computational resources without scaling pod number.

Thoughts?

**Comment by willgraf** [comment]
We have tested this and found that CPU cannot serve our models effectively.
