### ISSUE TITLE
file upload gives 206 return code

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#85]
When uploading the file [ecoli_generic.zip](https://storage.googleapis.com/deepcell-tpu/uploads/ecoli_generic.zip), I see a 206 return code for the upload call. Is this a problem?

**Comment by willgraf** [comment]
206 is a partial response, likely meaning that the file is being uploaded as multiple requests.  This should not be an issue.

Usually, 2XX HTTP codes are successful.
